[package]
name = "brish-plugin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
brish-core = { path = "../brish-core" }
brish-builtin = { path = "../brish-builtin" }
brish-engine = { path = "../brish-engine" }
brish-plugin-api = { path = "../brish-plugin-api" }
brish-theme = { path = "../brish-theme" }
reedline.workspace = true
nu-ansi-term.workspace = true
dirs.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true