[package]
name = "brish-builtin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
brish-core = { path = "../brish-core" }
brish-words = { path = "../brish-words" }
brish-platform = { path = "../brish-platform" }
brish-plugin-api = { path = "../brish-plugin-api" }
dirs.workspace = true
serde.workspace = true
toml.workspace = true
tempfile.workspace = true
toml_edit.workspace = true
